<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Tire
 * @package App\Models
 *
 * @property string $name
 * @property integer $width
 * @property integer $profile
 * @property string $diameter
 * @property integer $load_index
 * @property string $speed_index
 * @property integer $manual_distribution
 * @property integer $count
 * @property integer $price
 * @property int $manufacturer_id
 * @property int $tire_model_id
 */
class Tire extends Model
{
    /**
     * @var string[]
     */
    protected $casts = [
        'manual_distribution' => 'boolean',
    ];

    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'width',
        'profile',
        'diameter',
        'load_index',
        'speed_index',
        'manual_distribution',
        'count',
        'price',
        'tire_model_id',
        'manufacturer_id'
    ];

    /**
     * Формирование наименование исходя из параметров
     *
     * @param Tire $tire
     * @param TireModel $tireModel
     * @param Manufacturer $manufacturer
     * @return string
     */
    public function createName(Tire $tire, TireModel $tireModel = null, Manufacturer $manufacturer = null): string
    {
        $tireModelName = $tireModel ? $tireModel->name : '';
        $manufacturerName = $manufacturer ? $manufacturer->name : '';
        return "А/шина {$tire->width}/{$tire->profile} R{$tire->diameter} {$tire->load_index}{$tire->speed_index} {$tireModelName} {$manufacturerName}";
    }

    /**
     * Производитель шины
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function manufacturer()
    {
        return $this->belongsTo(Manufacturer::class);
    }

    /**
     * Модель шины
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function tireModel()
    {
        return $this->belongsTo(TireModel::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->name = $model->createName($model, $model->tireModel, $model->manufacturer);
        });

        self::updating(function ($model) {
            $model->name = $model->createName($model, $model->tireModel, $model->manufacturer);
        });
    }
}
