version: "2"

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 127.0.0.1:3315:3306
    environment:
      # Configuration here must match the settings of laravel
      - MYSQL_DATABASE=addamant
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123
    volumes:
      - ./databases/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
  laravel:
    image: evilfreelancer/dockavel:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:88:80
    environment:
      - APP_NAME=Tire-loader
      - APP_ENV=local
      - APP_KEY=base64:/4Blo+Nf2aSsBWP6Qf8q26WcTrkjfcFzadtD9addj64=
      - APP_DEBUG=true
      - APP_URL=127.0.0.1
      - LOG_CHANNEL=stack
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=
      - DB_DATABASE=addamant
      - DB_USERNAME=test
      - DB_PASSWORD=123
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - QUEUE_DRIVER=database
      - PUSHER_APP_ID=
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - PUSHER_APP_CLUSTER=mt1
      - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
      - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
      - PHP_XDEBUG_ENABLED=true
    volumes:
      - ./adamant/app:/app/app:cached
      - ./adamant/config:/app/config:cached
      - ./adamant/database:/app/database:cached
      - ./adamant/public:/app/public:cached
      - ./adamant/resources:/app/resources:cached
      - ./adamant/routes:/app/routes:cached
      # Required modules for system
      - ./adamant/vendor:/app/vendor:cached
      - ./adamant/node_modules:/app/node_modules:cached
      # Following folders must be writable in container for apache user
      # chown apache:apache -R storage/ bootstrap/
      - ./adamant/storage:/app/storage:cached
      - ./adamant/bootstrap:/app/bootstrap:cached
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:mysql
    restart: unless-stopped
    ports:
      - 127.0.0.1:8083:80
    environment:
        PMA_HOST: mysql
        PMA_USER: test
        PMA_PASSWORD: 123